# Generated by Django 6.0.4 on 2026-06-16 01:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nome da receita')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição curta')),
                ('origem', models.CharField(blank=True, max_length=200, verbose_name='Origem')),
                ('imagem_url', models.URLField(blank=True, verbose_name='URL da imagem')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('modo_preparo', models.TextField(verbose_name='Modo de preparo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='receitas.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de adição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por', to='receitas.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-data_adicao'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'receita'), name='favorito_unico_por_usuario')],
            },
        ),
    ]
