# Generated by Django 6.0.4 on 2026-06-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/fotos/', verbose_name='Imagem'),
        ),
    ]
